5487291

O deposito de um cheque de outra instituição foi realizado em duplicidade na conta poupança, como realizar o ajuste, ao tentar fazer o cancelamento da autenticação da mensagem de conta inexistente.


UA: 0728.12 - Amapora
Conta poupança 18265-6
Caixa 316
Autenticação 107
Cheque 020265
Valor 176.53
Cheque 851790
Valor 200,00
UPDATE VERSOES_INSTALADAS SET VERSAO_EXE = '2.13.06' WHERE  COD_SIST = '085' AND SCHEMA = 'AG0728'

--- Copiar de um banco para outro 

delete ag0728.ccr0asso;
--commit;
COPY FROM mauricio_mendes/1@coredbrep.sicredi.com.br TO developer/developer@coreperf2.sicredi.com.br append AG0728.ccr0asso USING select * from ag0728.ccr0asso ;

Select * from AG0728.ccr1movi ;
COPY FROM mauricio_mendes/1@coredbrep.sicredi.com.br TO developer/developer@coreperf2.sicredi.com.br append AG0728.ccr1movi USING  select FCODLANC,FDOCUM,FCONTA,FDLANCTO,FVALOR,FCCODTRANS,FCIDCOOP,FCIDPOSTO,FCIDUSUAR,FCAGORIGEM,FCSISTORIG,FDMOVIREF,FNCODJUST,FCCODREF,FDINCLUSAO,FNOIDMOVI,IE$0,IE$1,IE$2,IE$3,IE$4,IE$5,IE$6,IE$7,IE$8,RECNO,IS_DELETED  from ag0728.ccr1movi where fdlancto > to_date('23/12/2013')   ;

Select * from ag0728.ccrtmovi ;
COPY FROM mauricio_mendes/1@coredbrep.sicredi.com.br TO developer/developer@coreperf2.sicredi.com.br append AG0728.ccrtmovi USING  select RECNO,IS_DELETED,FCCODCAIXA,FDLANCTO,FCNRAUTENT,FCNRDOCUME,FCCODCARTE,FCTIPOPERA,FCNRCANCEL,FCCONTA,FCCODLANC,FNVALOR,FNIPMF,FCTRAN,FCCREDIDES,FCASSODEST,FLMULTDEPO,FCNUMCOB,FCCODCONT,FCCOMPTO,FNTPPES,FCPLASTICO,FLOFFLINE,FCIDCOOP,FCIDPOSTO,FCIDUSUAR,FCPOSTODES,IE$0,IE$1,IE$2,IE$3,IE$4,FCAGDEST,FCUSUAUTO,FCATO,FCLOTELCTO,IE$5,FNHRCONFDP,FNSITUDEPO,FCCODCONF,FCAUTREF from ag0728.ccrtmovi where fdlancto > to_date('23/12/2013')   ;

Select * from ag0728.ccr1paco ;
RECNO,IS_DELETED,FDULTINIC,F1PGDIAR,F1NDIAR,FDULTDIAR,FDIMPLSIST,FSDMEDIOM,FNDIASMIN,FNDIASEXC,FNFOLHAEXC,FSDMIN,FEXTRATO,FDDATAZERA,FNCHESPE,FNEXPOCCF,FDEXPOCCF,FNMESESCCF,FNEXPOSUST,FDEXPOSUST,FCVERSAO,FNSEQSAL,FCCOBDIF,FNDSEMJURO,FCMENSEXTR,FNSEQEXTR,FDLANCONTA,FCDIRCOMPE,FNSEQIRPF,FCRELEASE,FLRATEIOUP,FCPOSTORAT,FNESPFISUP,FNNUMFUNUP,FNESPFISPO,FNNUMFUNPO,FCCODEMPR,FCLIMCHPF,FCHISCHPF,FCLIMCHPJ,FCHISCHPJ,FCLIMCHPAS,FCHISCHPAS,FCEXTRELET,FCLIBBLOQ,FNCODJUST,FNPAALTLIM,FNPACANIMO,FCCDTARCCF


COPY FROM mauricio_mendes/1@coredbrep.sicredi.com.br TO developer/developer@coreperf2.sicredi.com.br append AG0728.ccr1paco USING select RECNO,IS_DELETED,FDULTINIC,F1PGDIAR,F1NDIAR,FDULTDIAR,FDIMPLSIST,FSDMEDIOM,FNDIASMIN,FNDIASEXC,FNFOLHAEXC,FSDMIN,FEXTRATO,FDDATAZERA,FNCHESPE,FNEXPOCCF,FDEXPOCCF,FNMESESCCF,FNEXPOSUST,FDEXPOSUST,FCVERSAO,FNSEQSAL,FCCOBDIF,FNDSEMJURO,FCMENSEXTR,FNSEQEXTR,FDLANCONTA,FCDIRCOMPE,FNSEQIRPF,FCRELEASE,FLRATEIOUP,FCPOSTORAT,FNESPFISUP,FNNUMFUNUP,FNESPFISPO,FNNUMFUNPO,FCCODEMPR,FCLIMCHPF,FCHISCHPF,FCLIMCHPJ,FCHISCHPJ,FCLIMCHPAS,FCHISCHPAS,FCEXTRELET,FCLIBBLOQ,FNCODJUST,FNPAALTLIM,FNPACANIMO,FCCDTARCCF ag0728.ccr1paco ;
